### ISSUE TITLE
Bug: `Unhandled exception. uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException`

### ISSUE THREAD

**Issue by jeroenhendricksen** [RaimondB/Detecticam#108]
I restarted my detecticam container running version `0.36.0` and was presented with the following exception:

```
[20:26:10.396] info: DetectiCam.BatchedCameraWatcherService[0]
      Process stopped.
Unhandled exception. uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at uPLibrary.Networking.M2Mqtt.MqttNetworkChannel.Send(Byte[] buffer)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Send(Byte[] msgBytes)
   --- End of inner exception stack trace ---
   at uPLibrary.Networking.M2Mqtt.MqttClient.Send(Byte[] msgBytes)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Send(MqttMsgBase msg)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Disconnect()
   at DetectiCam.Core.ResultProcessor.MqttPublisher.StopProcessingAsync(CancellationToken cancellationToken)
   at DetectiCam.Core.VideoCapturing.AnalyzedVideoFrameChannelConsumer.<>c__DisplayClass8_0.<<StopProcessingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[20:26:12.861] info: DetectiCam.Core.Detection.YoloBatchedDnnDetector[0]
```

This may be a bug?

This is what happened right before the above exception, maybe it helps:
```
[20:26:09.509] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Classifiy-objects ms:1262 for 3 images
[20:26:09.509] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      New result received for FRONTDOOR frame acquired at 02/07/2021 20:26:08.
[20:26:09.509] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      New result received for DRIVEWAY frame acquired at 02/07/2021 20:26:08.
[20:26:09.509] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      New result received for BARN frame acquired at 02/07/2021 20:26:08.
[20:26:09.937] info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
[20:26:09.960] info: DetectiCam.BatchedCameraWatcherService[0]
      Process received stop signal.
[20:26:09.975] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Stopping capturing tasks
[20:26:10.186] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Capture has stopped for FRONTDOOR
[20:26:10.205] warn: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Channel closed
[20:26:10.287] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Capture has stopped for DRIVEWAY
[20:26:10.288] warn: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Channel closed
[20:26:10.346] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Capture has stopped for BARN
[20:26:10.346] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Stopping merger
[20:26:10.346] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Stopping analyzer
[20:26:10.347] warn: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Channel closed
[20:26:10.348] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Stopping:completing merge channel!
[20:26:10.348] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Stopping:completing transform channel!
[20:26:10.349] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Stopping:completing consumer channel!
[20:26:10.352] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Stopping result publisher
[20:26:10.396] info: DetectiCam.BatchedCameraWatcherService[0]
      Process stopped.
```

**Comment by RaimondB** [comment]
This happens as part of the shutdown sequence. Apparently I am not shutting down completely in the current order. This is also a bit tricky, since the code is running on multiple threads. So an action for MQTT might still be running, while at the same time the TCP stack is shutting down. I see if I can reproduce it, but it is probably a timing issue.

**Comment by RaimondB** [comment]
I have not been able to reproduce this, so please let me know if you can and I'll reopen ;-)
