### ISSUE TITLE
Bug: `Invalid CallbackUrl for FRONTDOOR`

### ISSUE THREAD

**Issue by jeroenhendricksen** [RaimondB/Detecticam#121]
Detecticam has been running for 7 days straight. The config is static and was not changed. But, the next error still popped up:

```
[13:52:45.949] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Classifiy-objects ms:1149 for 3 images
[13:52:45.949] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      New result received for FRONTDOOR frame acquired at 02/15/2021 13:52:44.
[13:52:45.950] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      Person detected for frame acquired at 02/15/2021 13:52:44. Sending to result processors
[13:52:45.950] info: DetectiCam.Core.ResultProcessor.WebhookPublisher[0]
      Webhook notify for FRONTDOOR
[13:52:45.950] fail: DetectiCam.Core.ResultProcessor.WebhookPublisher[0]
      Invalid CallbackUrl for FRONTDOOR:
      System.UriFormatException: Invalid URI: The URI is empty.
         at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
         at DetectiCam.Core.ResultProcessor.WebhookPublisher.ProcessResultInternalAsync(VideoFrame frame)
[13:52:45.953] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      New result received for DRIVEWAY frame acquired at 02/15/2021 13:52:44.
[13:52:45.953] info: DetectiCam.Core.VideoCapturing.MultiStreamBatchedProcessorPipeline[0]
      New result received for BARN frame acquired at 02/15/2021 13:52:44.
```

I'm not using webhooks, only mqtt. Maybe there is an error in my config?

```
{
    "video-streams": [{
        "id": "FRONTDOOR",
        "path": "X",
        "callbackUrl": ""
    },{
        "id": "DRIVEWAY",
        "path": "Y",
        "callbackUrl": ""
    },{
        "id": "BARN",
        "path": "Z",
        "callbackUrl": ""
    }
    ],
    "mqtt-publisher": {
        "enabled": true,
        "server": "rabbitmq",
        "port": 1883,
        "topicPrefix": "detecticam",
        "clientId": "detecticam",
	"includeDetectedObjects": true,
	"topDetectedObjectsLimit" : 3
    },
    "capture-publisher": {
        "enabled": false
    }
}
```

**Comment by RaimondB** [comment]
I think you can just leave out the callbackUrl from the config completely.

**Comment by jeroenhendricksen** [comment]
> I think you can just leave out the callbackUrl from the config completely.

When I remove `callbackUrl` completely from the config, no MQTT message is sent any more...

**Comment by RaimondB** [comment]
> When I remove `callbackUrl` completely from the config, no MQTT message is sent any more...

Please recheck with the latest version, and provide your config so I can repro it. I now have expanded the integration test to  publish using mqtt and filecapture, but not use the callback. And here I do see the mqtt messages.

**Comment by jeroenhendricksen** [comment]
> > When I remove `callbackUrl` completely from the config, no MQTT message is sent any more...
> 
> Please recheck with the latest version, and provide your config so I can repro it. I now have expanded the integration test to publish using mqtt and filecapture, but not use the callback. And here I do see the mqtt messages.

My previous bug report was for version `0.36.0`. But now with the latest `0.36.4` version it works.

For the record, I'm now using this config (with the callBackUrl's removes):
```
{
    "video-streams": [{
        "id": "FRONTDOOR",
        "path": "rtsp://"
    },{
        "id": "DRIVEWAY",
        "path": "rtsp://"
    },{
        "id": "BARN",
        "path": "rtsp://"
    }],
    "mqtt-publisher": {
        "enabled": true,
        "server": "rabbitmq",
        "port": 1883,
        "topicPrefix": "detecticam",
        "clientId": "detecticam",
	"includeDetectedObjects": true,
	"topDetectedObjectsLimit" : 3
    },
    "capture-publisher": {
        "enabled": false
    },
    "yolo3": {
        "rootPath": "/config/yolov3-tiny",
        "configFile": "yolov3-tiny.cfg",
        "weightsFile": "yolov3-tiny.weights"
    }
}
```

And this is what detections look like on the MQTT-level:
```
mqtt sub -h rabbitmq -p 1883 --mqttVersion 3 -v -t "detecticam/detect-i-cam/#"
Client 'mqttRSjehtzm@rabbitmq' sending CONNECT MqttConnect{keepAlive=60, cleanSession=true}
Client 'mqttRSjehtzm@rabbitmq' received CONNACK MqttConnAck{returnCode=SUCCESS, sessionPresent=false}
Client 'mqttRSjehtzm@rabbitmq' sending SUBSCRIBE MqttSubscribe{subscriptions=[MqttSubscription{topicFilter=detecticam/detect-i-cam/#, qos=EXACTLY_ONCE}]}
Client 'mqttRSjehtzm@rabbitmq' received SUBACK MqttSubAck{returnCodes=[SUCCESS_MAXIMUM_QOS_1]}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.75607705,"BoundingBox":{"X":215,"Y":97,"Width":159,"Height":262}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.75607705,"BoundingBox":{"X":215,"Y":97,"Width":159,"Height":262}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=148byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.8608849,"BoundingBox":{"X":190,"Y":171,"Width":36,"Height":62}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.8608849,"BoundingBox":{"X":190,"Y":171,"Width":36,"Height":62}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=146byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.6268263,"BoundingBox":{"X":79,"Y":115,"Width":182,"Height":243}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.6268263,"BoundingBox":{"X":79,"Y":115,"Width":182,"Height":243}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=147byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.51189184,"BoundingBox":{"X":74,"Y":187,"Width":182,"Height":169}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.51189184,"BoundingBox":{"X":74,"Y":187,"Width":182,"Height":169}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=148byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.6480954,"BoundingBox":{"X":259,"Y":194,"Width":32,"Height":60}},{"Index":0,"Label":"person","Probability":0.6365391,"BoundingBox":{"X":181,"Y":198,"Width":47,"Height":50}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.6480954,"BoundingBox":{"X":259,"Y":194,"Width":32,"Height":60}},{"Index":0,"Label":"person","Probability":0.6365391,"BoundingBox":{"X":181,"Y":198,"Width":47,"Height":50}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=254byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.59258586,"BoundingBox":{"X":260,"Y":223,"Width":31,"Height":45}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.59258586,"BoundingBox":{"X":260,"Y":223,"Width":31,"Height":45}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=147byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.5090719,"BoundingBox":{"X":190,"Y":194,"Width":190,"Height":163}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.5090719,"BoundingBox":{"X":190,"Y":194,"Width":190,"Height":163}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=148byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.933868,"BoundingBox":{"X":196,"Y":108,"Width":136,"Height":256}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.933868,"BoundingBox":{"X":196,"Y":108,"Width":136,"Height":256}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=147byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.5840955,"BoundingBox":{"X":163,"Y":67,"Width":99,"Height":265}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.5840955,"BoundingBox":{"X":163,"Y":67,"Width":99,"Height":265}}]}') MqttPublish{topic=detecticam/detect-i-cam/BARN/state, payload=146byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.6675075,"BoundingBox":{"X":19,"Y":107,"Width":245,"Height":249}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.6675075,"BoundingBox":{"X":19,"Y":107,"Width":245,"Height":249}}]}') MqttPublish{topic=detecticam/detect-i-cam/FRONTDOOR/state, payload=147byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.5248195,"BoundingBox":{"X":18,"Y":97,"Width":269,"Height":262}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.5248195,"BoundingBox":{"X":18,"Y":97,"Width":269,"Height":262}}]}') MqttPublish{topic=detecticam/detect-i-cam/FRONTDOOR/state, payload=146byte, qos=AT_LEAST_ONCE, retain=false}
{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.7944442,"BoundingBox":{"X":191,"Y":53,"Width":202,"Height":302}}]}
Client 'mqttRSjehtzm@rabbitmq' received PUBLISH ('{"detection":true,"detectedObjects":[{"Index":0,"Label":"person","Probability":0.7944442,"BoundingBox":{"X":191,"Y":53,"Width":202,"Height":302}}]}') MqttPublish{topic=detecticam/detect-i-cam/FRONTDOOR/state, payload=147byte, qos=AT_LEAST_ONCE, retain=false}
```

Maybe  the problem was on my side after all, because I switches to `yolov3-tiny`, which has a factor 3 less CPU usage, but also seems to have a less sensitive detection in comparison with the built-in yolo. 

Thanks for your help!
